stages:
  - test # All jobs related for testing such as Unit Test
  - build

libro_test:
  stage: test
  script:
    - go test -v src/model/libro/libro_test.go
  tags:
    - golang 
    - test 

coleccion_test:
  stage: test
  script:
    - go test -v src/model/coleccion/coleccion_test.go 
  tags:
    - golang 
    - test 
autor_test:
  stage: test
  script:
    - go test -v src/model/autor/autor_test.go  
  tags:
    - golang 
    - test 


flutter_build_android: 
  stage: build
  script:
     - echo "Compilar"
  # artifacts:
  #   paths:
  #     - build/app/outputs/apk/release/app-release.apk
  #     - release/runer_gitlab.apk
  tags:
    - golang 
    - build 