# docker-compose up [--build]
version: '3'

services:
  app:
    container_name: biblioteca
    build: .
    ports:
      - 80:8000
    networks:
      - mongo-network
    environment:
      - MONGODB_URI=mongodb://TDTxLE:comemierda1@TDTxLE-mongodb:27017

networks:
  mongo-network:
    external: true
      
